version: "3"

services:
  database:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_DATABASE: "app"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ".cache/postgres:/var/lib/postgresql:rw"

  queue:
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"
